"""create notas fiscais table - fix

Revision ID: 219e02db4146
Revises: 4b8a11b0c775
Create Date: 2025-08-31 22:40:51.572377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219e02db4146'
down_revision: Union[str, None] = '4b8a11b0c775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_fiscais_id'), 'notas_fiscais', ['id'], unique=False)
    op.create_index(op.f('ix_notas_fiscais_numero'), 'notas_fiscais', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_fiscais_numero'), table_name='notas_fiscais')
    op.drop_index(op.f('ix_notas_fiscais_id'), table_name='notas_fiscais')
    op.drop_table('notas_fiscais')
    # ### end Alembic commands ###
