"""Criar tabela rfe010pes (cadastro pessoas)

Revision ID: b7f4cb2c516e
Revises: 219e02db4146
Create Date: 2025-09-09 19:06:22.676671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f4cb2c516e'
down_revision: Union[str, None] = '219e02db4146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfe010pes',
    sa.Column('codpes', sa.Integer(), nullable=False),
    sa.Column('tippes', sa.String(length=8), nullable=True),
    sa.Column('codtre', sa.Integer(), nullable=True),
    sa.Column('nompes', sa.String(length=100), nullable=False),
    sa.Column('pagcom', sa.String(length=1), nullable=True),
    sa.Column('fanpes', sa.String(length=100), nullable=True),
    sa.Column('endpes', sa.String(length=100), nullable=True),
    sa.Column('numpes', sa.String(length=10), nullable=True),
    sa.Column('baipes', sa.String(length=50), nullable=True),
    sa.Column('cplpes', sa.String(length=50), nullable=True),
    sa.Column('ceppes', sa.String(length=9), nullable=True),
    sa.Column('tespes', sa.String(length=15), nullable=True),
    sa.Column('faxpes', sa.String(length=15), nullable=True),
    sa.Column('celpes', sa.String(length=16), nullable=True),
    sa.Column('recpes', sa.String(length=15), nullable=True),
    sa.Column('obspes', sa.String(length=1000), nullable=True),
    sa.Column('cpfpes', sa.String(length=18), nullable=True),
    sa.Column('cnppes', sa.String(length=14), nullable=True),
    sa.Column('nrgpes', sa.String(length=18), nullable=True),
    sa.Column('iespes', sa.String(length=16), nullable=True),
    sa.Column('estpes', sa.String(length=2), nullable=True),
    sa.Column('cidpes', sa.String(length=100), nullable=True),
    sa.Column('codibg', sa.String(length=10), nullable=True),
    sa.Column('sitpes', sa.String(length=1), nullable=True),
    sa.Column('civpes', sa.String(length=15), nullable=True),
    sa.Column('sexpes', sa.String(length=1), nullable=True),
    sa.Column('logocl', sa.String(length=400), nullable=True),
    sa.Column('endcob', sa.String(length=100), nullable=True),
    sa.Column('numcob', sa.String(length=10), nullable=True),
    sa.Column('baicob', sa.String(length=50), nullable=True),
    sa.Column('cepcob', sa.String(length=50), nullable=True),
    sa.Column('ufcpes', sa.String(length=2), nullable=True),
    sa.Column('cdcpes', sa.String(length=100), nullable=True),
    sa.Column('cplcob', sa.String(length=30), nullable=True),
    sa.Column('tipseg', sa.Integer(), nullable=True),
    sa.Column('codtbp', sa.Integer(), nullable=True),
    sa.Column('limcre', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('limtit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dtacad', sa.Date(), nullable=True),
    sa.Column('dtaalt', sa.Date(), nullable=True),
    sa.Column('em1pes', sa.String(length=500), nullable=True),
    sa.Column('em2pes', sa.String(length=500), nullable=True),
    sa.Column('codemp', sa.Integer(), nullable=True),
    sa.Column('codfil', sa.Integer(), nullable=True),
    sa.Column('aliicm', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('aliipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('triicm', sa.String(length=1), nullable=False),
    sa.Column('triipi', sa.String(length=1), nullable=True),
    sa.Column('tripis', sa.String(length=1), nullable=True),
    sa.Column('tricof', sa.SmallInteger(), nullable=True),
    sa.Column('codrtb', sa.Integer(), nullable=True),
    sa.Column('peracr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('perdes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('perds1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('perds2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('perds3', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('codven', sa.Integer(), nullable=True),
    sa.Column('percsv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('percpd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('codcpg', sa.Integer(), nullable=True),
    sa.Column('codtra', sa.Integer(), nullable=True),
    sa.Column('ctato1', sa.String(length=40), nullable=True),
    sa.Column('ctato2', sa.String(length=40), nullable=True),
    sa.Column('codusu', sa.Integer(), nullable=True),
    sa.Column('usualt', sa.Integer(), nullable=True),
    sa.Column('cadcel', sa.String(length=1), nullable=False),
    sa.Column('diaven', sa.Integer(), nullable=True),
    sa.Column('vlrmes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('perate', sa.Integer(), nullable=True),
    sa.Column('txtctr', sa.String(length=2000), nullable=True),
    sa.Column('imppes', sa.String(length=1), nullable=True),
    sa.Column('iniseg', sa.Date(), nullable=True),
    sa.Column('finseg', sa.Date(), nullable=True),
    sa.Column('pascli', sa.String(length=70), nullable=True),
    sa.Column('confin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('codpes')
    )
    op.create_index('i010pes_codemp', 'rfe010pes', ['codemp'], unique=False)
    op.create_index('i010pes_codfil', 'rfe010pes', ['codfil'], unique=False)
    op.create_index('i010pes_codpes', 'rfe010pes', ['codpes'], unique=False)
    op.create_index('i010pes_codtre', 'rfe010pes', ['codtre'], unique=False)
    op.create_index('i010pes_cpfpes', 'rfe010pes', ['tippes', 'codtre', 'cpfpes', 'cnppes', 'codemp', 'codfil', 'nompes'], unique=True)
    op.create_index('i010pes_nompes', 'rfe010pes', ['nompes'], unique=False)
    op.create_index('i010pes_sitpes', 'rfe010pes', ['sitpes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('i010pes_sitpes', table_name='rfe010pes')
    op.drop_index('i010pes_nompes', table_name='rfe010pes')
    op.drop_index('i010pes_cpfpes', table_name='rfe010pes')
    op.drop_index('i010pes_codtre', table_name='rfe010pes')
    op.drop_index('i010pes_codpes', table_name='rfe010pes')
    op.drop_index('i010pes_codfil', table_name='rfe010pes')
    op.drop_index('i010pes_codemp', table_name='rfe010pes')
    op.drop_table('rfe010pes')
    # ### end Alembic commands ###
